language: node_js
node_js:
  - "18" 

cache:
  directories:
  - node_modules

install:
  - npm install

script:
  - ng lint
  - ng test --watch=false --browsers=ChromeHeadless
  - ng build --configuration production

deploy:
  provider: heroku
  api_key:
    secure: YOUR_ENCRYPTED_API_KEY
  app: face-reality