dist: focal
language: node_js
node_js:
- '18'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- ng lint
- ng build --configuration production
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
